### ISSUE TITLE
Parser accepts invalid numerical values

### ISSUE THREAD

**Issue by LeopoldArkham** [LeopoldArkham/Molten#10]
The spec states:
>"Similar to integers, you may use underscores to enhance readability. Each underscore must be surrounded by at least one digit."

I think we currently allow leading and trailing underscores: This should be fixed.
Auditing that part of the code to makes sure there aren't any other issues regarding what we allow/disallow regarding ints and floats would be a good thing in general.

This should probably be looked at together with #2

The code for this is in the Int, float, datetime arm of the `parse_val()` function in `parser.rs`

**Comment by kimsnj** [comment]
Hey,

I am still pretty new to this. But I'll give a try at this issue during the week-end.
