### ISSUE TITLE
One nightly dependency away from testing in stable Rust

### ISSUE THREAD

**Issue by jeremydavis519** [LeopoldArkham/Molten#36]
I've noticed that, with the latest stable version of Rust (1.22.1), this entire project can be compiled. The only thing that forces us to use a nightly compiler is the dependence on the `test-case-derive` crate, and specifically its use of `#![feature(proc_macro)]`. (I confirmed it by getting rid of that dependency and successfully running the tests with the stable compiler.) It would be nice to rely only on stable features as much as possible. We can already use the stable compiler for release builds, but using two different versions might lead to some unexpected bugs.

That said, if there's a reason for us to use `test-case-derive`, that's fine. But if it's okay to get rid of it, I don't mind restructuring the test code for that purpose. The changes that would be needed at this point are pretty minor.

**Comment by LeopoldArkham** [comment]
If you can submit a PR for the tests that still looks, let's say, 80% as good, I'll be glad to merge it! Otherwise, as long as we can build on stable, I'm not worried overmuch either.
