### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by LeopoldArkham** [LeopoldArkham/Molten#6]
This is to discuss how error reporting should work.

Thoughts:
- Making attempts to overcome recoverable errors is not currently planned
- It would be nice if the error type contained the position where the error occurs. What should that look like?
- This project is very amenable to using `error-chain`, but I've seen people raise concerns about it that have made me shy away from it. Thoughts on whether this is justified and alternatives if it is?
- ...

**Comment by ehuss** [comment]
I've been watching the `error-chain` development closely recently.  I think some of the big concerns have been addressed within the past month.  In particular, performance should be much better (it now lazily retrieves backtrace symbols only when needed), and memory usage has been reduced.  It still has some issues and is in flux, but I don't think it would be a bad idea to try it.

I was using error-chain in my prototype, which captured the line/column in the error.  I can try a PR so you can see what it might look like.

**Comment by LeopoldArkham** [comment]
Ah that's good news. In that case I'd definitely like to look at what you have.
